### ISSUE TITLE
Win10 Startmenu not scrollable

### ISSUE THREAD

**Issue by MCMatzeHD** [ttencate/taekwindow#113] opened 2018-03-17 14:35 UTC
When I try to scroll the apps-list in the Windows 10 Startmenu (The menu that you open with the Windows-Key), it can't be scrolled. After taekwindow is disabled, it works.

Edit: Same happens with the search menu (cortana).

**Comment by ttencate** [comment] 2018-03-18 08:42
Thanks for your report. I can reproduce this only if I set `Scroll wheel behaviour` to `Scroll the window under the cursor`. If you're using that, please switch to `Scroll the focused window` instead. This option is rather mis-named nowadays, and should really be called `Windows default`, because Windows 10 actually _does_ scroll the window under the cursor by default. That's tracked in #110.

I'm closing this issue now. If the above solution doesn't work for you, feel free to comment or reopen!

**Closed as completed by ttencate** 2018-03-18 08:42 UTC

**Comment by MCMatzeHD** [comment] 2018-03-18 12:16
Thanks, found the Option in Windows 10 which wasn't enabled. Now it works with switching the options.
